const $=id=>document.getElementById(id);const fmt=n=>n>=1e6?(n/1e6).toFixed(2)+'M':n>=1e3?(n/1e3).toFixed(1)+'K':Math.floor(n).toLocaleString();
const holes=[{par:4,distance:312,goal:80},{par:3,distance:168,goal:110},{par:5,distance:486,goal:150},{par:4,distance:338,goal:210},{par:4,distance:355,goal:285},{par:3,distance:192,goal:370},{par:5,distance:521,goal:520},{par:4,distance:401,goal:690},{par:5,distance:548,goal:900}];
const upgrades=[
{id:'club',name:'Polished Club',desc:'+2 base shot power',base:18,growth:1.55,icon:'2% 8%',power:2},
{id:'caddy',name:'Pocket Caddie',desc:'+1.5 coins each second',base:45,growth:1.7,icon:'17% 12%',idle:1.5},
{id:'range',name:'Practice Range',desc:'+12% all earnings',base:120,growth:1.8,icon:'48% 45%',mult:.12},
{id:'fans',name:'Gallery Rope',desc:'+1 fan per hole and +4 power',base:230,growth:1.9,icon:'18% 78%',power:4,fans:1},
{id:'cart',name:'Clockwork Cart',desc:'+7 coins each second',base:520,growth:2.05,icon:'73% 47%',idle:7}
];
const worlds=[
{id:'highland',name:'Highland Links',image:'assets/courses/highland-links.webp',weather:'Coastal gale • 18 mph',mods:['+35% shot power','+25% Legacy earned','−20% idle income'],power:1.35,idle:.8,legacy:1.25},
{id:'desert',name:'Desert Championship',image:'assets/courses/desert-championship.webp',weather:'Dry crosswind • 12 mph',mods:['+60% tournament rewards','+20% upgrade costs','+8% shot power'],reward:1.6,cost:1.2,power:1.08},
{id:'tropical',name:'Tropical Paradise',image:'assets/courses/tropical-paradise.webp',weather:'Ocean breeze • 7 mph',mods:['Idle income doubled','+50% fan gain','−15% shot power'],idle:2,fans:1.5,power:.85}
];
const home={name:'Home Course',image:'assets/courses/home-course.webp',weather:'Calm morning • 3 mph'};let state;
function freshState(){return{coins:0,fans:0,legacy:0,hole:0,progress:0,shots:0,cleared:0,best:0,streak:0,levels:Object.fromEntries(upgrades.map(u=>[u.id,0])),world:null,runMultiplier:1,won:false,pendingLegacy:0,lastTick:Date.now()}}
function load(){const blank=freshState();try{const saved=JSON.parse(localStorage.getItem('fairwayFablesSave')||'null');state=saved?{...blank,...saved,levels:{...blank.levels,...saved.levels}}:blank}catch{state=blank}const elapsed=Math.max(0,(Date.now()-(state.lastTick||Date.now()))/1000);state.coins+=Math.min(elapsed,14400)*idleRate();state.lastTick=Date.now()}
function save(show=true){state.lastTick=Date.now();localStorage.setItem('fairwayFablesSave',JSON.stringify(state));if(show)toast('Game saved')}
function worldObj(){return worlds.find(w=>w.id===state.world)||{}}
function upgradeCost(u){return Math.floor(u.base*Math.pow(u.growth,state.levels[u.id])*(worldObj().cost||1))}
function earningsMult(){return state.runMultiplier*(worldObj().reward||1)*(1+state.levels.range*.12)}
function shotPower(){let p=12+state.legacy*1.5;for(const u of upgrades)p+=(u.power||0)*state.levels[u.id];return p*(worldObj().power||1)}
function idleRate(){let r=(state?.levels?.caddy||0)*1.5+(state?.levels?.cart||0)*7;return r*(worldObj().idle||1)*earningsMult()}
function fanGain(){return(1+state.levels.fans)*(worldObj().fans||1)}
function renderUpgrades(){$('upgradeList').innerHTML=upgrades.map(u=>{const cost=upgradeCost(u);return`<div class="upgrade-item"><div class="upgrade-icon" style="background-position:${u.icon}"></div><div class="upgrade-copy"><h3>${u.name} <small>Lv. ${state.levels[u.id]}</small></h3><p>${u.desc}</p></div><button class="upgrade-button" data-buy="${u.id}" ${state.coins<cost?'disabled':''}>${fmt(cost)} coins</button></div>`}).join('')}
function renderTrack(){$('tournamentTrack').innerHTML=holes.map((h,i)=>`<div class="hole-node ${i<state.hole?'complete':''} ${i===state.hole&&!state.won?'current':''}"><div><strong>${i+1}</strong>Par ${h.par}</div></div>`).join('')}
function render(){const h=holes[Math.min(state.hole,8)],world=worldObj(),course=state.world?world:home;$('courseImage').src=course.image;$('courseImage').alt=course.name;$('weatherChip').textContent=course.weather;$('coins').textContent=fmt(state.coins);$('fans').textContent=fmt(state.fans);$('legacy').textContent=fmt(state.legacy);$('hole').textContent=`${Math.min(state.hole+1,9)} / 9`;$('par').textContent=h.par;$('distance').textContent=h.distance+' yd';$('multiplier').textContent='×'+earningsMult().toFixed(2);$('shotsTaken').textContent=state.shots;$('holesCleared').textContent=state.cleared;$('bestStreak').textContent=state.best;$('currentWorld').textContent=course.name;$('incomeRate').textContent=fmt(idleRate())+' / sec';$('tournamentStatus').textContent=state.won?'Cup won!':`Hole ${state.hole+1}`;const pct=Math.min(100,state.progress/h.goal*100);$('shotProgress').style.width=pct+'%';$('shotPercent').textContent=Math.floor(pct)+'%';$('shotLabel').textContent=state.won?'The Founder’s Cup is yours.':pct?`${Math.ceil(h.goal-state.progress)} power to the pin`:'Ready at the tee';$('runMessage').textContent=state.won?`Your run earned ${state.pendingLegacy} Legacy. Choose a new world.`:'Win the nine-hole Founder’s Cup to unlock your first prestige choice.';renderUpgrades();renderTrack()}
function animateShot(reward){const art=$('courseArt'),pip=$('pipSprite'),float=$('floatingReward');pip.className='pip-sprite swing';art.classList.add('shooting');float.textContent='+'+fmt(reward)+' coins';float.classList.remove('show');void float.offsetWidth;float.classList.add('show');setTimeout(()=>{art.classList.remove('shooting');pip.className='pip-sprite ready'},500)}
function swing(){if(state.won)return;state.shots++;const variance=.82+Math.random()*.38,power=shotPower()*variance,reward=power*.72*earningsMult();state.progress+=power;state.coins+=reward;animateShot(reward);if(state.progress>=holes[state.hole].goal)completeHole();else state.streak=0;render()}
function completeHole(){const h=holes[state.hole];state.cleared++;state.streak++;state.best=Math.max(state.best,state.streak);state.coins+=(h.goal*1.8+state.fans*2)*earningsMult();state.fans+=fanGain();state.progress=0;state.hole++;$('pipSprite').className='pip-sprite celebrate';toast(`Hole ${state.hole} cleared!`);if(state.hole>=holes.length){state.won=true;state.pendingLegacy=Math.max(3,Math.floor((state.fans+state.cleared*3)/8*(worldObj().legacy||1)));setTimeout(showPrestige,700)}}
function buy(id){const u=upgrades.find(x=>x.id===id),cost=upgradeCost(u);if(state.coins>=cost){state.coins-=cost;state.levels[id]++;toast(`${u.name} upgraded`);render()}}
function showPrestige(){$('worldGrid').innerHTML=worlds.map(w=>`<article class="world-card"><img src="${w.image}" alt="${w.name}"><div class="world-card-body"><h3>${w.name}</h3><ul>${w.mods.map(m=>`<li>${m}</li>`).join('')}</ul><button class="world-button" data-world="${w.id}">Enter with +${state.pendingLegacy} Legacy</button></div></article>`).join('');$('prestigeDialog').showModal()}
function prestige(id){const legacy=state.legacy+(state.pendingLegacy||3);state=freshState();state.legacy=legacy;state.world=id;state.runMultiplier=1+legacy*.05;save(false);$('prestigeDialog').close();toast(`Entered ${worldObj().name}`);render()}
function toast(msg){$('toast').textContent=msg;$('toast').classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>$('toast').classList.remove('show'),1700)}
$('swingButton').addEventListener('click',swing);$('upgradeList').addEventListener('click',e=>{if(e.target.dataset.buy)buy(e.target.dataset.buy)});$('worldGrid').addEventListener('click',e=>{if(e.target.dataset.world)prestige(e.target.dataset.world)});$('saveButton').addEventListener('click',()=>save());$('resetButton').addEventListener('click',()=>{if(confirm('Erase this save and begin again?')){state=freshState();save(false);render()}});document.addEventListener('visibilitychange',()=>{if(document.hidden)save(false)});
load();render();setInterval(()=>{state.coins+=idleRate()/4;render()},250);setInterval(()=>save(false),10000);
